---
openapi: 3.0.2
info:
  title: NeuroQuery Webapp
  version: 1.0.0
  description: An API to help the NeuroBridge portal interact with the NeuroQuery API

servers:
  - url: https://neurobridges.apps.renci.org

paths:
  "/neuroquery":
    get:
      description: Interact with the NeuroQuery API
      operationId: neuroquery
      parameters:
      - name: searchTerms
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: The neuroquery terms
          content:
            application/json:
              schema:
                 type: object
                 properties:
                   data:
                     type: array
                     items:
                       type: object
                       properties:
                         pmid:
                           type: integer
                         pubmed_url:
                           type: string
                         similarity:
                           type: number
                         title:
                           type: string
