# Put sterling-specific config in this file, which overrides the defaults in values.yaml
ingress:
  enabled: true
  # https://wiki.renci.org/index.php/Kubernetes_Cloud/Sterling#How_to_set_up_Ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/whitelist-source-range: "0.0.0.0/0,::/0"

  hosts:
    - host: api.neurobridges.org
      paths:
        - path: /
  tls:
   - secretName: api.neurobridges.org-tls
     hosts:
       - api.neurobridges.org
